# fly.toml app configuration file generated for mr-hello1 on 2023-07-10T20:13:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mr-hello1"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
